# Generated by Django 6.1.1 on 2026-09-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('img', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('tecnologias', models.ManyToManyField(related_name='proyectos', to='proyectos.tecnologia')),
            ],
        ),
    ]
